version: "3.9"
services:
  churn-service:
    build:
      context: .
      args:
        # Optionally pin base image digest here
        # PY_BASE: python:3.11-slim@sha256:<digest>
        PY_BASE: python:3.11-slim
    image: churn:service
    command: ["uvicorn", "ml_portfolio_churn.service:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - SERVICE_TOKEN=${SERVICE_TOKEN:-changeme}
      - CHURN_ROOT=/app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    # Healthcheck hits /metrics which is intentionally public even if SERVICE_TOKEN is set
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/metrics\")' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Optional: Prometheus to scrape /metrics
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   healthcheck:
  #     test: ["CMD-SHELL", "wget -qO- http://localhost:9090/-/ready || exit 1"]
  #     interval: 15s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s
  #   restart: unless-stopped

